twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
        article_img_directory: '/images/articles/'
        article_url: '/article/'

when@test:
    twig:
        strict_variables: true
